module.exports = [
    [
        "Anakims Nemesis Zakaron",
        "Beastlord Behemoth",
        "Faf Herald Lokness",
        "Korim",
        "Meanas Anor",
        "Palibati Queen Themis",
        "Roar Skylancer",
        "Raid Boss Von Helman",
        "Hope Immortality Mardil",
        "Doom Blade Tanatos",
        "Vanor Chief Kandra",
        "Wdragon Priest Sheshark",
        "Antaras Cloe",
        "Krokian Padisha Sobekk",
        "Benom",
        "Bloody Empress Decarbia",
        "Ipos The Death Lord",
        "Shax The Death Lord",
        "Last Lesser Olkuth",
        "Storm Winged Naga",
        "Ocean Flame Ashakiel",
        "Geyser Guardian Hestia",
        "Last Lesser Glaki",
        "Shuriel Fire Of Wrath",
        "Cherub Garacsia",
    ], [
        "Uruka",
        "Amber",
        "Varka Chief Horuth",
        "Varka Commnder Mos",
    ]
]